title: Sanat Tarihi Ders Kitab??
description: ??a??da?? d??nemden geriye do??ru sanat tarihini izleyen bir ders kitab??
baseurl: "" # if the site is deployed at the root of a domain
url: "https://dogacol.github.io/sanat-tarihi" # your GitHub Pages URL
markdown: kramdown
theme: minima
